// Generated from public/bills.json.
// Run `npm run generate-bill-summaries` to refresh.

export const PREWRITTEN_BILL_SUMMARIES: Record<string, string> = {
  "C-1": "This bill continues the traditional pro forma first bill in the House of Commons.",
  "C-2": "This bill would strengthen Canada-U.S. border security and make related public safety changes.",
  "C-3": "This bill would restore and extend citizenship by descent in certain cases and create a substantial-connection test for future cases.",
  "C-4": "This bill would cut the lowest personal income tax rate, create a temporary GST rebate for first-time home buyers, repeal the fuel charge, and change party privacy rules.",
  "C-5": "This bill would reduce interprovincial trade barriers and improve labour mobility in Canada.",
  "C-6": "This bill authorizes federal spending for the start of the 2025-26 fiscal year.",
  "C-7": "This bill authorizes additional federal spending for the 2025-26 fiscal year.",
  "C-8": "This bill would create new cyber security rules, amend the Telecommunications Act, and make related changes.",
  "C-9": "This bill would strengthen laws on hate propaganda, hate crimes, and access to religious or cultural places.",
  "C-10": "This bill would create a Commissioner for Modern Treaty Implementation.",
  "C-11": "This bill would modernize the military justice system and amend related laws.",
  "C-12": "This bill would tighten border security, strengthen immigration enforcement, and make related security changes.",
  "C-13": "This bill would implement the United Kingdom’s accession protocol to the CPTPP trade agreement.",
  "C-14": "This bill would change criminal, youth justice, and military law on bail and sentencing.",
  "C-15": "This bill would implement measures from the federal budget tabled on November 4, 2025.",
  "C-16": "This bill would change criminal and correctional law on child protection, gender-based violence, delays, and related measures.",
  "C-17": "This bill authorizes government spending for the first part of the 2025-26 fiscal year.",
  "C-18": "This bill would implement the Canada-Indonesia comprehensive economic partnership agreement.",
  "C-19": "This bill would temporarily increase the GST/HST credit through the Canada Groceries and Essentials Benefit.",
  "C-20": "This bill would establish Build Canada Homes as a federal Crown corporation.",
  "C-21": "This bill would bring the Red River Métis self-government treaty into law and make related changes.",
  "C-22": "This bill would modernize lawful access rules for getting data and information during investigations.",
  "C-23": "This bill authorizes federal spending for the remainder of the 2025-26 fiscal year.",
  "C-24": "This bill authorizes federal spending for the start of the 2026-27 fiscal year.",
  "C-25": "This bill would change federal election rules and rename certain electoral districts.",
  "C-26": "This bill would authorize federal payments aimed at improving housing supply.",
  "C-27": "This bill would bring the final self-government agreement for the Tlegohli Got’ine into law.",
  "C-201": "This bill would amend the Canada Health Act on mental, addictions and substance use health services.",
  "C-202": "This bill would amend the Department of Foreign Affairs, Trade and Development Act on supply management.",
  "C-203": "This bill would designate Ukrainian Heritage Month.",
  "C-204": "This bill would amend the Income Tax Act on volunteer firefighting and search and rescue volunteer tax credit.",
  "C-205": "This bill would amend the National Housing Strategy Act.",
  "C-206": "This bill would create a national strategy on brain injuries.",
  "C-207": "This bill would amend the Canada Pension Plan.",
  "C-208": "This bill would recognize a national livestock brand as a symbol of Canada and western frontier heritage.",
  "C-209": "This bill would establish Albanian Heritage Month.",
  "C-210": "This bill would amend the Constitution Act, 1867 on oath of office.",
  "C-211": "This bill would amend the Income Tax Act and the Canada Pension Plan on deeming provision.",
  "C-212": "This bill would create an ombud office for the Department of Citizenship and Immigration and make related legal changes.",
  "C-213": "This bill would amend the Immigration and Refugee Protection Act on cessation of refugee protection.",
  "C-214": "This bill would require development of a national renewable energy strategy.",
  "C-215": "This bill would amend the Marine Liability Act on national strategy respecting pollution caused by shipping container spills.",
  "C-216": "This bill would enact the Protection of Minors in the Digital Age Act and amend two related laws.",
  "C-217": "This bill would amend the Canada Student Financial Assistance Act and the Income Tax Act.",
  "C-218": "This bill would amend the Criminal Code on medical assistance in dying.",
  "C-219": "This bill would strengthen Magnitsky-style sanctions and foreign affairs rules and make related broadcasting changes.",
  "C-220": "This bill would amend the Criminal Code on immigration status in sentencing.",
  "C-221": "This bill would amend the Corrections and Conditional Release Act on disclosure of information to victims.",
  "C-222": "This bill would amend the Employment Insurance Act and the Canada Labour Code on death of a child.",
  "C-223": "This bill would amend the Divorce Act.",
  "C-224": "This bill would amend the Food and Drugs Act on natural health products.",
  "C-225": "This bill would amend the Criminal Code.",
  "C-226": "This bill would create a national framework to improve food price transparency.",
  "C-227": "This bill would create a national strategy on housing for young Canadians.",
  "C-228": "This bill would amend the Department of Foreign Affairs, Trade and Development Act on prior review of treaties by Parliament.",
  "C-229": "This bill would create a national framework respecting attention deficit hyperactivity disorder.",
  "C-230": "This bill would amend the Financial Administration Act, make related changes to other laws, and address debt forgiveness registry.",
  "C-231": "This bill would amend the Youth Criminal Justice Act.",
  "C-232": "This bill would amend the Corrections and Conditional Release Act on maximum security offenders.",
  "C-233": "This bill would amend the Export and Import Permits Act.",
  "C-234": "This bill would create Living Donor Recognition Medal.",
  "C-235": "This bill would amend the Criminal Code on increasing parole ineligibility.",
  "C-236": "This bill would change criminal and corrections law to address the ongoing victimization of homicide victims’ families.",
  "C-237": "This bill would amend the Fisheries Act on atlantic groundfish fisheries.",
  "C-238": "This bill would amend the Criminal Code on restitution orders.",
  "C-239": "This bill would amend the Canada Health Act on accountability.",
  "C-240": "This bill would change criminal, corrections, and drug laws to promote offender rehabilitation.",
  "C-241": "This bill would create a national strategy respecting flood and drought forecasting.",
  "C-242": "This bill would change criminal justice rules on bail and related Department of Justice provisions.",
  "C-243": "This bill would amend the Corrections and Conditional Release Act on parole review.",
  "C-244": "This bill would amend the Canadian Environmental Protection Act, 1999 and the Wrecked, Abandoned or Hazardous Vessels Act.",
  "C-245": "This bill would amend the Canadian Multiculturalism Act on non-application in Quebec.",
  "C-246": "This bill would amend the Criminal Code on consecutive sentences for sexual offences.",
  "C-247": "This bill would amend the Canada Labour Code.",
  "C-248": "This bill would require a pan-Canadian conference on time change.",
  "C-249": "This bill would amend the Employment Insurance Act on combined weeks of benefits rule and certain benefits.",
  "C-250": "This bill would amend the Canada Labour Code on flight attendants.",
  "C-251": "This bill would amend the Customs Act and the Customs Tariff on forced labour and child labour.",
  "C-252": "This bill would create national day of remembrance to honour Canadian Armed Forces members who have lost their lives in peacetime in Canada.",
  "C-253": "This bill would create a national framework for guaranteed livable basic income.",
  "C-254": "This bill would amend the Criminal Code on promotion of hatred against Indigenous peoples.",
  "C-255": "This bill would amend the Criminal Code on mischief — religious property.",
  "C-256": "This bill would amend several laws relating to survivor pension benefits.",
  "C-257": "This bill would amend the Criminal Code on promotion of terrorist activity or group.",
  "C-258": "This bill would amend the Criminal Code to address the Supreme Court of Canada decision in R. v. Jordan.",
  "C-259": "This bill would amend the Canada Labour Code on fair representation.",
  "C-260": "This bill would amend the Criminal Code on medical assistance in dying — protection against coercion.",
  "C-261": "This bill would amend the Old Age Security Act on amount of full pension.",
  "C-262": "This bill would amend the Canada Post Corporation Act.",
  "C-263": "This bill would create a national framework for silver alerts to help locate missing older adults.",
  "C-264": "This bill would repeal certain restrictions on shipping.",
  "C-265": "This bill would amend the Food and Drugs Act on list of Therapeutic Products Pre-approved for Special Access.",
  "C-266": "This bill would create a national framework respecting skilled trades and labour mobility.",
  "C-267": "This bill would create a national framework to improve the durability of electronics and essential home appliances.",
  "C-268": "This bill would establish the Spectrum Policy Framework for Canada.",
  "C-269": "This bill would amend the Income Tax Act on heat recovery tax credit.",
  "C-270": "This bill would amend the Criminal Code on defence of person.",
  "C-271": "This bill would amend the Criminal Code on scrap metal trafficking and essential infrastructure protection.",
  "C-272": "This bill would amend the Controlled Drugs and Substances Act on supervised drug consumption sites.",
  "S-1": "This bill continues the traditional pro forma first bill in the Senate.",
  "S-2": "This bill would expand Indian Act registration entitlements.",
  "S-3": "This bill would update measurement and inspection rules for weights, electricity, and gas systems.",
  "S-4": "This bill would amend the Energy Efficiency Act.",
  "S-5": "This bill would require health IT systems to work together and stop vendors from blocking health data sharing.",
  "S-6": "This bill would further harmonize federal law with Quebec civil law and update related statutes.",
  "S-201": "This bill would create national framework on sickle cell disease.",
  "S-202": "This bill would amend the Food and Drugs Act on warning label on alcoholic beverages.",
  "S-203": "This bill would prohibit promotion of alcoholic beverages.",
  "S-204": "This bill would create a national framework on heart failure.",
  "S-205": "This bill would change correctional law to limit isolation and strengthen oversight and remedies in prisons.",
  "S-206": "This bill would create a national framework for guaranteed livable basic income.",
  "S-207": "This bill would amend the Criminal Records Act, make related changes to other laws, and repeal regulation.",
  "S-208": "This bill would amend the Criminal Code on independence of the judiciary.",
  "S-209": "This bill would restrict young people’s online access to pornographic material.",
  "S-210": "This bill would designate Ukrainian Heritage Month.",
  "S-211": "This bill would create national framework on sports betting advertising.",
  "S-212": "This bill would create national strategy for children and youth in Canada.",
  "S-213": "This bill would amend the Canada Elections Act on demographic information.",
  "S-214": "This bill would change sanctions law to allow the disposal of foreign state assets.",
  "S-215": "This bill would designate National Immigration Month.",
  "S-216": "This bill would declare Chignecto Isthmus Dykeland System and related works to be for the general advantage of Canada.",
  "S-217": "This bill would require reporting on unpaid income tax to help measure the tax gap.",
  "S-218": "This bill would amend the Constitution Act, 1982 on notwithstanding clause.",
  "S-219": "This bill would establish Judicial Independence Day.",
  "S-220": "This bill would designate Hellenic Heritage Month.",
  "S-221": "This bill would provide for the recognition of the Canada jay as the national bird of Canada.",
  "S-222": "This bill would lower the federal voting age to 16 for elections and referendums.",
  "S-223": "This bill would amend the Royal Canadian Mounted Police Act.",
  "S-224": "This bill would amend the Director of Public Prosecutions Act.",
  "S-225": "This bill would establish National Thanadelthur Day.",
  "S-226": "This bill would designate Jury Duty Appreciation Week.",
  "S-227": "This bill would designate Arab Heritage Month.",
  "S-228": "This bill would amend the Criminal Code on sterilization procedures.",
  "S-229": "This bill would amend the National Capital Act on gatineau Park.",
  "S-230": "This bill would require a national strategy for soil health protection, conservation and enhancement.",
  "S-231": "This bill would amend the Criminal Code on medical assistance in dying.",
  "S-232": "This bill would set rules on the use and limits of non-disclosure agreements.",
  "S-233": "This bill would amend the Criminal Code on assault against persons who provide health services and first responders.",
  "S-234": "This bill would create national framework for fetal alcohol spectrum disorder.",
  "S-235": "This bill would establish a national strategy to combat human trafficking.",
  "S-236": "This bill would amend the Canadian Victims Bill of Rights and create a framework for implementing the rights of victims of crime.",
  "S-237": "This bill would designate Cities and Municipalities Day.",
  "S-238": "This bill would enact the Climate-Aligned Finance Act and make related changes to other laws.",
  "S-239": "This bill would amend the Competition Act.",
  "S-240": "This bill would create a notwithstanding-clause exception for certain mandatory minimum sentences involving child sexual abuse material offences.",
  "S-241": "This bill would amend the Criminal Code and the Indian Act.",
  "S-242": "This bill would require national action to prevent intimate partner violence.",
  "S-243": "This bill would create a national framework for women’s health in Canada.",
  "S-244": "This bill would designate National Diffuse Intrinsic Pontine Glioma Awareness Day.",
  "S-245": "This bill would designate National Blanket Ceremony Day.",
  "S-1001": "This bill would let Gore Mutual Insurance Company continue as a Quebec corporation.",
}
